from zoautil_py.ztypes import ZOAUResponse as ZOAUResponse

class _ZOAUExtendableException(Exception):
    message: str
    response: ZOAUResponse
    def __init__(self, response_obj: ZOAUResponse) -> None: ...

class ZOAUException(_ZOAUExtendableException): ...
class DatasetCreateException(_ZOAUExtendableException): ...
class DatasetFetchException(_ZOAUExtendableException): ...
class DatasetFormatException(_ZOAUExtendableException): ...
class DatasetWriteException(_ZOAUExtendableException): ...
class DatasetVerificationError(Exception): ...
class GenerationDataGroupDeleteException(_ZOAUExtendableException): ...
class GenerationDataGroupClearException(_ZOAUExtendableException): ...
class GenerationDataGroupFetchException(_ZOAUExtendableException): ...
class GenerationDataGroupViewInvalidName(Exception): ...
class GenerationDataGroupViewInvalidState(Exception): ...
class GenerationDataGroupCreateException(Exception): ...
class JobFetchException(_ZOAUExtendableException): ...
class JobSubmitException(_ZOAUExtendableException): ...
class JobCancelException(_ZOAUExtendableException): ...
class JobPurgeException(_ZOAUExtendableException): ...
class DDQueryException(_ZOAUExtendableException): ...
class JobCancelConfirmException(Exception): ...
class JobPurgeConfirmException(Exception): ...
class MissingEnvironmentVariable(Exception): ...
class MissingFunctionParameter(Exception): ...
