import logging
from zoautil_py import datasets as datasets
from zoautil_py.common import clean_dataset_name as clean_dataset_name, parse_universal_arguments as parse_universal_arguments, zoau_json_load as zoau_json_load
from zoautil_py.core import call_zoau_library as call_zoau_library
from zoautil_py.exceptions import DatasetFetchException as DatasetFetchException, GenerationDataGroupClearException as GenerationDataGroupClearException, GenerationDataGroupCreateException as GenerationDataGroupCreateException, GenerationDataGroupDeleteException as GenerationDataGroupDeleteException, GenerationDataGroupFetchException as GenerationDataGroupFetchException, GenerationDataGroupViewInvalidName as GenerationDataGroupViewInvalidName, GenerationDataGroupViewInvalidState as GenerationDataGroupViewInvalidState
from zoautil_py.ztypes import ZOAUResponse as ZOAUResponse

logger: logging.Logger

class GenerationDataGroupView:
    def __init__(self, name: str, **kwargs) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value) -> None: ...
    @property
    def limit(self) -> int: ...
    @property
    def scratch(self) -> bool: ...
    @property
    def empty(self) -> bool: ...
    @property
    def order(self): ...
    @property
    def purge(self) -> bool: ...
    @property
    def extended(self) -> bool: ...
    def generations(self, **kwargs) -> tuple[datasets.Dataset]: ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    def __next__(self) -> datasets.Dataset: ...
    def delete(self, **kwargs) -> None: ...
    def clear(self) -> None: ...

def create(name: str, limit: int, *, empty: bool = False, scratch: bool = False, purge: bool = False, extended: bool = False, fifo: bool = False, **kwargs) -> GenerationDataGroupView: ...
def list_gdg_names(pattern: str, **kwargs) -> list[str]: ...
def exists(name: str, **kwargs): ...
