from zoautil_py.common import clean_dataset_name as clean_dataset_name, clean_shell_input as clean_shell_input, parse_universal_arguments as parse_universal_arguments
from zoautil_py.core import call_zoau_library as call_zoau_library
from zoautil_py.ztypes import ZOAUResponse as ZOAUResponse

def search_library(command: str, find: str, *args, **kwargs) -> ZOAUResponse: ...
def list_library(command: str, *args, **kwargs) -> ZOAUResponse: ...
def find_member_in_library(command: str, member: str, *args, **kwargs) -> ZOAUResponse: ...
