import logging
from zoautil_py.common import clean_dataset_name as clean_dataset_name, parse_universal_arguments as parse_universal_arguments, zoau_json_load as zoau_json_load
from zoautil_py.core import call_zoau_library as call_zoau_library
from zoautil_py.exceptions import MissingFunctionParameter as MissingFunctionParameter
from zoautil_py.utilities import find_member_in_library as find_member_in_library, list_library as list_library, search_library as search_library
from zoautil_py.ztypes import ZOAUResponse as ZOAUResponse

logger: logging.Logger

def read_console(options: str = '-r', json_output: bool = False, **kwargs) -> str: ...
def list_data_classes(*args, **kwargs) -> list[str]: ...
def list_linklist(*args, **kwargs) -> list[str]: ...
def list_parmlib(*args, **kwargs) -> list[str]: ...
def list_proclib(*args, **kwargs) -> list[str]: ...
def find_linklist(member: str, *args, **kwargs) -> str: ...
def find_parmlib(member: str, *args, **kwargs) -> str: ...
def find_proclib(member: str, *args, **kwargs) -> str: ...
def search_parmlib(find: str, *args, **kwargs) -> str: ...
def search_proclib(find: str, *args, **kwargs) -> str: ...
def apf(*args, **kwargs) -> ZOAUResponse: ...
def zinfo(*args, **kwargs) -> str: ...
